# Generated by Django 5.2.1 on 2026-06-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filteroptionvalue',
            name='filter_option',
        ),
        migrations.DeleteModel(
            name='FilterOption',
        ),
        migrations.DeleteModel(
            name='FilterOptionValue',
        ),
    ]
